# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1a2e4efde8273eed3329c21800f8db5f1b2ed772a1d4b99404bff28654e82bdbe27b03c661f02cee2e1dbcf3c2ccad73e0f06520e281bb6136ad9b40fc95788

test:
  secret_key_base: 05fb3e304d0c38886252d5e1a6322cd736357d120089f1f5d5a23776047220ead50dd95a6ad707906511e40ba3a473cca06b0c1f98caa9c454301123ca698e80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
